//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IAT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEM_TAG,VALUE
        ///EMaintExponent,0.00082
        ///GrowthEnergyIntercept1,6.7
        ///GrowthEnergyIntercept2,20.3
        ///GrowthEfficiency,1.09
        ///BaseAnimalEquivalent,450
        ///GreenDietMax,0.98
        ///GreenDietCoefficient,0.15
        ///GreenDietZero,0.04
        ///IntakeTropicalQuality,0.16
        ///IntakeCoefficientQuality,1.7
        ///IntakeCoefficientBiomass,0.006
        ///MilkIntakeMaximum,20
        ///MilkLWTFodderSubstitutionProportion,0.2
        ///MaxJuvenileIntake,0.035
        ///ProportionalDiscountDueToMilk,0.3
        ///ProportionOfMaxWeightToSurvive,0.5
        ///LactatingPotentialModifierConstantA,0.42
        ///Lactating [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Resources_CLEM {
            get {
                return ResourceManager.GetString("Resources_CLEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAT_TABLE,IAT_ROW,IAT_NAME,CLEM_TAG,PROP
        ///Ruminant coefficients,1,SRW,SRWFemale,1
        ///Ruminant coefficients,2,birth_SRW,SRWBirth,1
        ///Ruminant coefficients,3,Critical_cow_wt,CriticalCowWeight,0.01
        ///Ruminant coefficients,4,grwth_coeff1,AgeGrowthRateCoefficient,1
        ///Ruminant coefficients,5,grwth_coeff2,SRWGrowthScalar,1
        ///Ruminant coefficients,6,km_coeff,EMaintEfficiencyCoefficient,1
        ///Ruminant coefficients,7,km_incpt,EMaintEfficiencyIntercept,1
        ///Ruminant coefficients,8,kg_coeff,EGrowthEfficiencyCoefficient,1
        ///Ruminan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Resources_IAT {
            get {
                return ResourceManager.GetString("Resources_IAT", resourceCulture);
            }
        }
    }
}
